# Generated by Django 4.2.1 on 2023-08-29 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0011_saduser_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
