# Generated by Django 4.2.1 on 2023-08-29 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0012_alter_user_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="saduser", name="year",),
        migrations.AlterField(
            model_name="saduser",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
