# Generated by Django 4.2.1 on 2023-09-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WPBLAPP", "0013_remove_saduser_year_alter_saduser_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="id",),
        migrations.AlterField(
            model_name="user",
            name="num",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
